default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: financely_development
test:
  <<: *default
  database: financely_test

production:
  <<: *default
  database: financely